# Generated by Django 5.1.6 on 2025-11-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Мета-заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета-описание')),
                ('show_breadcrumbs', models.BooleanField(default=True, verbose_name='Показывать хлебные крошки')),
                ('show_organization_info', models.BooleanField(default=True, verbose_name='Показывать информацию об организации')),
            ],
            options={
                'verbose_name': 'Настройки страницы контактов',
                'verbose_name_plural': 'Настройки страницы контактов',
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название раздела')),
                ('section_type', models.CharField(choices=[('documents', 'Прием документов'), ('services', 'Услуги одного окна'), ('media', 'Контакты для СМИ'), ('it', 'Техническая поддержка IT'), ('general', 'Общие контакты')], max_length=20, unique=True, verbose_name='Тип раздела')),
                ('department_name', models.CharField(blank=True, max_length=200, verbose_name='Название отдела/подразделения')),
                ('description', models.TextField(blank=True, verbose_name='Описание раздела')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('additional_phones', models.JSONField(blank=True, default=list, verbose_name='Дополнительные телефоны')),
                ('additional_emails', models.JSONField(blank=True, default=list, verbose_name='Дополнительные email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('work_hours', models.TextField(blank=True, verbose_name='Время работы')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Раздел контактов',
                'verbose_name_plural': 'Разделы контактов',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название организации')),
                ('full_name', models.CharField(max_length=500, verbose_name='Полное наименование')),
                ('general_phone', models.CharField(max_length=20, verbose_name='Основной телефон')),
                ('general_email', models.EmailField(max_length=254, verbose_name='Основной email')),
                ('additional_phones', models.JSONField(blank=True, default=list, verbose_name='Дополнительные телефоны')),
                ('address', models.TextField(verbose_name='Юридический адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание организации')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='contacts/logos/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Информация об организации',
                'verbose_name_plural': 'Информация об организации',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название соцсети')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('icon_class', models.CharField(blank=True, max_length=50, verbose_name='CSS класс иконки')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
                'ordering': ['order', 'name'],
            },
        ),
    ]
