# Generated by Django 5.1.6 on 2025-11-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название мероприятия')),
                ('event_type', models.CharField(choices=[('current', 'Идут сейчас'), ('upcoming', 'Предстоящие'), ('past', 'Прошедшие')], default='upcoming', max_length=20, verbose_name='Тип мероприятия')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('detailed_description', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Изображение')),
                ('date', models.DateField(verbose_name='Дата мероприятия')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время мероприятия')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость входа')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатное мероприятие')),
                ('registration_url', models.URLField(blank=True, verbose_name='Ссылка для регистрации')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Место проведения')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактный email')),
                ('organizers', models.TextField(blank=True, verbose_name='Организаторы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['event_type', 'date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='InterestingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название программы')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='interesting_programs/', verbose_name='Изображение')),
                ('top_image', models.ImageField(blank=True, null=True, upload_to='interesting_programs/top/', verbose_name='Верхнее изображение')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('start_date', models.CharField(max_length=100, verbose_name='Начало обучения')),
                ('duration', models.CharField(max_length=100, verbose_name='Длительность')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('detailed_description', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Интересная программа',
                'verbose_name_plural': 'Интересные программы',
                'ordering': ['order', 'title'],
            },
        ),
    ]
