# Generated by Django 5.1.6 on 2025-11-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('agreement', models.BooleanField(default=False, verbose_name='موافقة على الشروط')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('subscribed_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
            ],
            options={
                'verbose_name': 'مشترك في النشرة الإخبارية',
                'verbose_name_plural': 'المشتركون في النشرة الإخبارية',
                'ordering': ['-created_at'],
            },
        ),
    ]
