# Generated by Django 5.2.6 on 2025-11-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_newslettersubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'ordering': ['-created_at'], 'verbose_name': ' Подпишитесь на рассылку новостей', 'verbose_name_plural': ' Подписчики рассылки новостей '},
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name=' Согласие с условиями'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name=' Дата регистрации  '),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name=' электронная почта'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активный'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='subscribed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
    ]
