# Generated by Django 5.2.8 on 2025-12-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_newslettersubscription_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Подписчик рассылки новостей', 'verbose_name_plural': 'Подписчики рассылки новостей'},
        ),
        migrations.AddField(
            model_name='event',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/hero/', verbose_name='Главное изображение (баннер)'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие с условиями'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
