# Generated by Django 5.2.8 on 2025-12-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_newslettersubscription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(default='events_page', max_length=100, unique=True, verbose_name='Название страницы')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='page_hero/', verbose_name='Главное изображение')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок изображения')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='Подзаголовок изображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активировать изображение')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройки страницы',
                'verbose_name_plural': 'Настройки страниц',
                'ordering': ['page_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Подписка на рассылку', 'verbose_name_plural': 'Подписки на рассылку'},
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие с условиями'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
