# Generated by Django 5.2.8 on 2025-12-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_pagesettings_alter_newslettersubscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesettings',
            name='hero_image',
            field=models.ImageField(blank=True, default='page_hero/default_hero.jpg', null=True, upload_to='page_hero/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Присоединяйтесь к нашим событиям', verbose_name='Подзаголовок изображения'),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='hero_title',
            field=models.CharField(default='Мероприятия', max_length=200, verbose_name='Заголовок изображения'),
        ),
    ]
