# Generated by Django 5.2.8 on 2025-12-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_pagesettings_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Изображение для верхней части страницы мероприятия. Если не загружено, будет использоваться основное изображение.', null=True, upload_to='events/hero/', verbose_name='Главное изображение для детальной страницы'),
        ),
        migrations.AddField(
            model_name='event',
            name='hero_subtitle',
            field=models.TextField(blank=True, verbose_name='Подзаголовок для главного изображения'),
        ),
        migrations.AddField(
            model_name='event',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Если оставить пустым, будет использоваться название мероприятия', max_length=200, verbose_name='Заголовок для главного изображения'),
        ),
        migrations.AddField(
            model_name='event',
            name='show_hero_image',
            field=models.BooleanField(default=True, verbose_name='Показывать главное изображение'),
        ),
    ]
