# Generated by Django 5.2.8 on 2025-12-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_hero_image_event_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='show_hero_image',
        ),
    ]
