# Generated by Django 5.2.8 on 2025-12-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_event_hero_image_remove_event_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Главное изображение, которое появляется в верхней части страницы мероприятия', null=True, upload_to='events/hero/', verbose_name='Главное изображение страницы'),
        ),
    ]
