# Generated by Django 5.2.8 on 2025-12-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hero_image',
        ),
    ]
