# Generated by Django 5.2.8 on 2025-12-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_remove_event_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesettings',
            name='page_type',
            field=models.CharField(choices=[('events_page', 'Страница мероприятий'), ('gallery_page', 'Страница фотогалереи'), ('event_detail_page', 'Страница деталей мероприятия')], default='events_page', max_length=20, verbose_name='Тип страницы'),
        ),
    ]
