# Generated by Django 5.2.8 on 2025-12-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_pagesettings_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesettings',
            name='page_type',
            field=models.CharField(choices=[('events_page', 'Страница мероприятий'), ('gallery_page', 'Страница фотогалереи')], default='events_page', max_length=20, verbose_name='Тип страницы'),
        ),
    ]
