# Generated by Django 5.2.8 on 2026-02-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_pagesettings_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video_description',
            field=models.TextField(blank=True, verbose_name='Описание видео'),
        ),
        migrations.AddField(
            model_name='event',
            name='video_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок видео'),
        ),
        migrations.AddField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео (YouTube / Vimeo)'),
        ),
    ]
