# Generated by Django 5.2.8 on 2026-02-12 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_video_description_event_video_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='video_description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='video_title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='video_url',
        ),
    ]
