# Generated by Django 5.2.8 on 2026-02-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_event_video_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.FileField(blank=True, help_text='Загрузите короткое видео (до 30 секунд, MP4) о том, как добраться до места.', null=True, upload_to='events/videos/', verbose_name='Видео (как дойти)'),
        ),
        migrations.AddField(
            model_name='event',
            name='video_title',
            field=models.CharField(blank=True, default='Как дойти?', max_length=200, verbose_name='Заголовок видео'),
        ),
    ]
