# Generated by Django 5.2.8 on 2026-03-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_event_video_event_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesettings',
            name='newsletter_image',
            field=models.ImageField(blank=True, help_text='Изображение, отображаемое справа от формы подписки', null=True, upload_to='newsletter/', verbose_name='Изображение для рассылки'),
        ),
    ]
