# Generated by Django 5.2.8 on 2026-03-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_remove_pagesettings_newsletter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesettings',
            name='newsletter_success_image',
            field=models.ImageField(blank=True, help_text='Это изображение появится после успешной подписки на новости.', null=True, upload_to='newsletter/', verbose_name='Изображение успешной подписки'),
        ),
    ]
