# Generated by Django 5.2.8 on 2026-03-16 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_company'),
        ('events', '0022_pagesettings_newsletter_success_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='event',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='interestingprogram',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interesting_programs', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='photo',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='accounts.company', verbose_name='Компания'),
        ),
    ]
