# Generated by Django 5.2.8 on 2026-01-28 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название проекта')),
                ('project_type', models.CharField(choices=[('government', 'Госзаказы'), ('corporate', 'Корпоративные проекты'), ('grants', 'Гранты и финансирование'), ('contests', 'Конкурсные мероприятия'), ('youth', 'Молодежный ученый совет'), ('social', 'Социальные инициативы'), ('targeted', 'Целевое обучение'), ('patents', 'Патенты'), ('conferences', 'Конференции')], max_length=20, verbose_name='Тип проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('short_description', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('sidebar_title', models.CharField(blank=True, max_length=500, verbose_name='Заголовок боковой панели')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Изображение')),
                ('description_image', models.ImageField(blank=True, null=True, upload_to='projects/description/', verbose_name='Изображение над описанием')),
                ('presentation_file', models.FileField(blank=True, null=True, upload_to='projects/presentations/', verbose_name='Файл презентации')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('active', 'В разработке'), ('completed', 'Реализован'), ('planned', 'Планируется')], default='active', max_length=20, verbose_name='Статус')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Бюджет')),
                ('participants_count', models.IntegerField(default=0, verbose_name='Количество участников')),
                ('results', models.TextField(blank=True, verbose_name='Результаты проекта')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый проект')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Категория проектов',
                'verbose_name_plural': 'Категории проектов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=20, unique=True, verbose_name='Уникальный ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('organization', models.CharField(blank=True, max_length=300, verbose_name='Организация')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Предполагаемый бюджет')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Срок реализации')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('reviewed', 'Рассмотрено'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Предложение проекта',
                'verbose_name_plural': 'Предложения проектов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок слайда')),
                ('image', models.ImageField(upload_to='project_slides/', verbose_name='Изображение слайда')),
                ('description', models.TextField(blank=True, verbose_name='Описание слайда')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Слайд проектов',
                'verbose_name_plural': 'Слайды проектов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Запрос обратной связи',
                'verbose_name_plural': 'Запросы обратной связи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectcategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок изображения')),
                ('image', models.ImageField(upload_to='project_gallery/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание изображения')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Связанный проект (необязательно)')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Галерея изображений',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО участника')),
                ('role', models.CharField(choices=[('leader', 'Руководитель'), ('member', 'Участник'), ('consultant', 'Консультант'), ('partner', 'Партнер')], max_length=20, verbose_name='Роль')),
                ('organization', models.CharField(blank=True, max_length=300, verbose_name='Организация')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проектов',
            },
        ),
        migrations.CreateModel(
            name='ProjectPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название партнера')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='projects/partners/', verbose_name='Логотип партнера')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('description', models.TextField(blank=True, verbose_name='Описание партнера')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Партнер проекта',
                'verbose_name_plural': 'Партнеры проектов',
                'ordering': ['order', 'name'],
            },
        ),
    ]
