# Generated by Django 5.2.8 on 2026-01-31 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=20, unique=True, verbose_name='Уникальный ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок заявки')),
                ('description', models.TextField(verbose_name='Описание заявки')),
                ('person_type', models.CharField(default='individual', max_length=20, verbose_name='Тип лица')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('organization', models.CharField(blank=True, max_length=300, verbose_name='Организация')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=20, verbose_name='КПП')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('reviewed', 'Рассмотрено'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Заявка на участие в проекте',
                'verbose_name_plural': 'Заявки на участие в проектах',
                'ordering': ['-created_at'],
            },
        ),
    ]
