# Generated by Django 5.2.8 on 2026-01-31 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_delete_projectjoinrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=20, unique=True, verbose_name='Уникальный ID')),
                ('person_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('legal', 'Юридическое лицо')], default='individual', max_length=20, verbose_name='Тип лица')),
                ('full_name_individual', models.CharField(blank=True, max_length=200, verbose_name='ФИО (физ. лицо)')),
                ('phone_individual', models.CharField(blank=True, max_length=20, verbose_name='Телефон (физ. лицо)')),
                ('email_individual', models.EmailField(blank=True, max_length=254, verbose_name='Email (физ. лицо)')),
                ('address_individual', models.TextField(blank=True, verbose_name='Адрес (физ. лицо)')),
                ('comments_individual', models.TextField(blank=True, verbose_name='Комментарии (физ. лицо)')),
                ('full_name_legal', models.CharField(blank=True, max_length=200, verbose_name='Ответственное лицо (юр. лицо)')),
                ('phone_legal', models.CharField(blank=True, max_length=20, verbose_name='Телефон (юр. лицо)')),
                ('email_legal', models.EmailField(blank=True, max_length=254, verbose_name='Email (юр. лицо)')),
                ('company_name', models.CharField(blank=True, max_length=300, verbose_name='Название компании')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=20, verbose_name='КПП')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('comments_legal', models.TextField(blank=True, verbose_name='Комментарии (юр. лицо)')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('reviewed', 'Рассмотрено'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Запрос на участие в проекте',
                'verbose_name_plural': 'Запросы на участие в проектах',
                'ordering': ['-created_at'],
            },
        ),
    ]
