# Generated by Django 5.2.8 on 2026-01-31 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectjoinrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectJoinRequest',
        ),
    ]
