# Generated by Django 5.2.8 on 2026-03-16 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_company'),
        ('projects', '0008_projectjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='projectgallery',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_galleries', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='projectjoinrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_join_requests', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='projectpartner',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_partners', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_proposals', to='accounts.company', verbose_name='Компания'),
        ),
    ]
