# Generated by Django 5.2.6 on 2025-11-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_show_gallery_newsgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='show_gallery',
        ),
        migrations.DeleteModel(
            name='NewsGallery',
        ),
    ]
