# Generated by Django 5.2.8 on 2025-12-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_show_gallery_delete_newsgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок для баннера на странице списка новостей', max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, help_text='Краткое описание под заголовком', verbose_name='Подзаголовок')),
                ('image', models.ImageField(help_text='Рекомендуемый размер: 1920x600 пикселей', upload_to='news/hero/', verbose_name='Фоновое изображение')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать баннер на странице', verbose_name='Активно')),
                ('show_button', models.BooleanField(default=True, verbose_name='Показывать кнопку')),
                ('button_text', models.CharField(default='Посмотреть все новости', max_length=50, verbose_name='Текст кнопки')),
                ('button_link', models.CharField(default='#', help_text='Можно указать внутреннюю ссылку или внешнюю URL', max_length=200, verbose_name='Ссылка кнопки')),
                ('order', models.IntegerField(default=0, help_text='Чем меньше число, тем выше отображается', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Баннер страницы новостей',
                'verbose_name_plural': 'Баннеры страницы новостей',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
