# Generated by Django 5.2.6 on 2025-11-14 15:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressCenterPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Пресс-центр', max_length=200, verbose_name='Заголовок')),
                ('background_image', models.ImageField(upload_to='press_center/', verbose_name='Фоновое изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Страница Пресс-центра',
                'verbose_name_plural': 'Страница Пресс-центра',
            },
        ),
        migrations.CreateModel(
            name='PublicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Номер заявки')),
                ('organization', models.CharField(max_length=200, verbose_name='Название организации')),
                ('theme', models.CharField(max_length=200, verbose_name='Тема публикации')),
                ('desired_dates', models.CharField(max_length=100, verbose_name='Желаемые даты публикации')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Контактное лицо')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('additional_wishes', models.TextField(blank=True, verbose_name='Дополнительные пожелания')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заявка на публикацию',
                'verbose_name_plural': 'Заявки на публикацию',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PressCenterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='press_center/images/', verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('press_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='press_center.presscenterpage')),
            ],
            options={
                'verbose_name': 'Изображение Пресс-центра',
                'verbose_name_plural': 'Изображения Пресс-центра',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PressPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('research_type', models.CharField(choices=[('news', 'Новости'), ('article', 'Статьи'), ('report', 'Отчеты'), ('analysis', 'Аналитика')], default='news', max_length=50, verbose_name='Тип публикации')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='press_publications/', verbose_name='Изображение')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Автор')),
                ('file', models.FileField(blank=True, null=True, upload_to='press_publications/files/', verbose_name='Файл публикации')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('tags', models.ManyToManyField(blank=True, related_name='press_publications', to='research.researchtag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Публикация Пресс-центра',
                'verbose_name_plural': 'Публикации Пресс-центра',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
    ]
