# Generated by Django 5.2.8 on 2026-02-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presscenterpage',
            name='rules_file',
            field=models.FileField(blank=True, null=True, upload_to='press_center/rules/', verbose_name='Файл правил публикации'),
        ),
    ]
