# Generated by Django 5.2.8 on 2026-02-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press_center', '0003_remove_presscenterpage_rules_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PressPublication',
        ),
    ]
