# Generated by Django 5.2.8 on 2026-02-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press_center', '0004_delete_presspublication'),
    ]

    operations = [
        migrations.AddField(
            model_name='presscenterpage',
            name='rules_file',
            field=models.FileField(blank=True, help_text='PDF или другой документ, который пользователи смогут скачать', null=True, upload_to='press_center/rules/', verbose_name='Файл с правилами публикации'),
        ),
    ]
