# Generated by Django 5.2.8 on 2026-02-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press_center', '0005_presscenterpage_rules_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presscenterpage',
            name='rules_file',
        ),
    ]
