# Generated by Django 5.2.8 on 2026-02-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press_center', '0006_remove_presscenterpage_rules_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='presscenterpage',
            name='publication_rules_file',
            field=models.FileField(blank=True, help_text='Загрузите PDF файл с правилами публикации', null=True, upload_to='press_center/rules/', verbose_name='Файл с правилами публикации'),
        ),
    ]
