# Generated by Django 5.2.8 on 2026-02-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press_center', '0008_remove_presscenterpage_publication_rules_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='presscenterpage',
            name='publication_rules_file',
            field=models.FileField(blank=True, null=True, upload_to='press_center/rules/', verbose_name='Файл правил публикации'),
        ),
    ]
