# Generated by Django 5.2.8 on 2026-03-16 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_company'),
        ('press_center', '0009_presscenterpage_publication_rules_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_requests', to='accounts.company', verbose_name='Компания'),
        ),
    ]
