# Generated by Django 5.2.8 on 2026-03-14 13:33

import applicants.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=20, unique=True, verbose_name='Номер заявки')),
                ('contact_person', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Имя содержит недопустимые символы.', regex='^[^<>{}()\\[\\]\\\\\\/$%^&*+=|~`]+$')], verbose_name='Контактное лицо')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('additional_notes', models.TextField(blank=True, default='', verbose_name='Дополнительные пожелания')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('completed', 'Завершена')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заявка поступающего',
                'verbose_name_plural': 'Заявки поступающих',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='applicant_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png']), applicants.models.validate_file_size], verbose_name='Файл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Документ для поступающих',
                'verbose_name_plural': 'Документы для поступающих',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Поступающим', max_length=200, verbose_name='Заголовок')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='applicants/', verbose_name='Фоновое изображение')),
                ('rocket_image', models.ImageField(blank=True, null=True, upload_to='applicants/', verbose_name='Изображение ракеты')),
                ('conditions_file', models.FileField(blank=True, null=True, upload_to='applicants/conditions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), applicants.models.validate_file_size], verbose_name='Файл с условиями приема')),
                ('enrollment_conditions_file', models.FileField(blank=True, null=True, upload_to='applicants/enrollment_conditions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), applicants.models.validate_file_size], verbose_name='Файл с условиями поступления')),
                ('programs_list_file', models.FileField(blank=True, null=True, upload_to='applicants/programs_list/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), applicants.models.validate_file_size], verbose_name='Файл с перечнем образовательных программ')),
                ('benefits_file', models.FileField(blank=True, null=True, upload_to='applicants/benefits/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), applicants.models.validate_file_size], verbose_name='Файл с льготами и особыми условиями')),
                ('contract_sample_file', models.FileField(blank=True, null=True, upload_to='applicants/contracts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), applicants.models.validate_file_size], verbose_name='Образец договора на обучение')),
                ('useful_links_file', models.FileField(blank=True, null=True, upload_to='applicants/useful_links/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), applicants.models.validate_file_size], verbose_name='Полезные ссылки и документы')),
                ('methods_review_text', models.CharField(blank=True, default='Заявки рассматриваются в течение пяти рабочих дней с момента подачи.', max_length=300, verbose_name='Текст о рассмотрении заявок')),
                ('methods_login_text', models.CharField(blank=True, default='Для подачи документов дистанционно нужно авторизироваться в личном кабинете.', max_length=300, verbose_name='Текст об авторизации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Страница Поступающим',
                'verbose_name_plural': 'Страница Поступающим',
            },
        ),
        migrations.CreateModel(
            name='ApplicationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('icon_svg', models.TextField(help_text='Вставьте код SVG основной иконки', verbose_name='SVG иконки')),
                ('question_svg', models.TextField(help_text='Вставьте код SVG знака вопроса (можно одинаковый для всех)', verbose_name='SVG знака вопроса')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Способ подачи документов',
                'verbose_name_plural': 'Способы подачи документов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(help_text='Загрузите изображение (PNG, JPG, JPEG)', upload_to='enrollment_stages/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Изображение этапа')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Этап зачисления',
                'verbose_name_plural': 'Этапы зачисления',
                'ordering': ['order'],
            },
        ),
    ]
