# Generated by Django 5.2.8 on 2026-03-16 21:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_company'),
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantapplication',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_applications', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='applicantapplication',
            name='contact_person',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Имя содержит недопустимые символы.', regex='^[^<>{}()\\[\\]\\\\\\/$%^&*+=|~`]+$')], verbose_name='Контактное лицо'),
        ),
    ]
