# Generated by Django 5.2.8 on 2026-03-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Название изображения, отображаемое при наведении', max_length=200, verbose_name='Название (необязательно)')),
                ('image', models.ImageField(upload_to='patents/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения в слайдере', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать изображение в слайдере', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Изображение патента',
                'verbose_name_plural': 'Изображения патентов',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
