# Generated by Django 5.2.8 on 2026-03-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patentimage',
            name='caption',
            field=models.TextField(blank=True, help_text='Отображается под слайдером, можно использовать длинный текст', verbose_name='Текст под изображением'),
        ),
    ]
