# Generated by Django 5.2.8 on 2025-12-17 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='team/', verbose_name='Фото')),
                ('position', models.CharField(max_length=300, verbose_name='Должность')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('qualifications', models.TextField(blank=True, verbose_name='Квалификации и образование')),
                ('experience', models.TextField(blank=True, verbose_name='Опыт работы')),
                ('member_type', models.CharField(choices=[('teacher', 'Преподаватель'), ('staff', 'Сотрудник')], max_length=10, verbose_name='Тип')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Члены команды',
                'ordering': ['member_type', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, verbose_name='Роль преподавателя')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduleprogram', verbose_name='Программа')),
                ('teacher', models.ForeignKey(limit_choices_to={'member_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to='staff.teammember', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Программа преподавателя',
                'verbose_name_plural': 'Программы преподавателей',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
