# Generated by Django 5.2.8 on 2025-12-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_pagehero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='member_type',
            field=models.CharField(choices=[('teacher', 'Преподаватель'), ('staff', 'Сотрудник'), ('educational_council', 'Учебный совет')], max_length=20, verbose_name='Тип'),
        ),
    ]
