# Generated by Django 5.2.8 on 2025-12-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_teammember_member_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название отделения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#7F1726', max_length=7, verbose_name='Цвет маркера')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='staff.department', verbose_name='Отделения'),
        ),
    ]
