# Generated by Django 5.2.8 on 2025-12-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_department_teammember_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='team_members', to='staff.department', verbose_name='Отделения'),
        ),
    ]
