# Generated by Django 5.2.8 on 2025-12-23 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_teammember_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='departments',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
