# Generated by Django 5.2.8 on 2025-12-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_heroimage'),
        ('staff', '0006_remove_teammember_departments_delete_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='team_members', to='departments.department', verbose_name='Отделения'),
        ),
    ]
