# Generated by Django 5.2.8 on 2026-02-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_teammember_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.TextField(verbose_name='Должность'),
        ),
    ]
