# Generated by Django 5.2.8 on 2026-03-16 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_company'),
        ('staff', '0008_alter_teammember_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprogram',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_programs', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='accounts.company', verbose_name='Компания'),
        ),
    ]
