# Generated by Django 5.1.6 on 2025-11-13 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='г. Москва, Садовая-Спасская 19к1\n(м. Красные ворота)', verbose_name='Адрес')),
                ('phone', models.CharField(default='+7 (968) 418-44-88', max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(default='info.fta@mail.ru', max_length=254, verbose_name='E-mail')),
                ('director', models.CharField(default='Солтанмурадова Заира Рустамовна', max_length=200, verbose_name='Руководитель')),
                ('position_document', models.CharField(default='Положение об услугах одного окна', max_length=300, verbose_name='Название документа положения')),
                ('position_file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Файл положения')),
                ('department', models.CharField(default='Управление развития персонала', max_length=200, verbose_name='Входит в состав')),
                ('working_days', models.CharField(default='Пн-Пт: 9:00 - 18:00', max_length=100, verbose_name='Рабочие дни')),
                ('lunch_break', models.CharField(default='Обед: 13:00 - 14:00', max_length=100, verbose_name='Обеденный перерыв')),
                ('weekend', models.CharField(default='Сб-Вс: выходной', max_length=100, verbose_name='Выходные')),
                ('working_description', models.TextField(default='Мы готовы помочь вам в удобное время', verbose_name='Описание графика работы')),
            ],
            options={
                'verbose_name': 'Основные сведения',
                'verbose_name_plural': 'Основные сведения',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание услуги')),
                ('icon_class', models.CharField(help_text='Например: fas fa-file-medical', max_length=100, verbose_name='Класс иконки')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок страницы')),
                ('content', models.TextField(verbose_name='Содержание страницы')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета-описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='single_window.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Страница услуги',
                'verbose_name_plural': 'Страницы услуг',
            },
        ),
    ]
