# Generated by Django 5.1.6 on 2025-11-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_window', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServicePage',
        ),
    ]
