# Generated by Django 5.1.6 on 2025-11-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_window', '0002_remove_servicepage_service_delete_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('maternal_capital', 'Направить материнский капитал для обучения детей'), ('personal_data', 'Изменить личные данные, отчислиться, оформить каникулы'), ('education_credit', 'Образовательный кредит с господдержкой'), ('education_discount', 'Получить льготу на образование'), ('other', 'Другие услуги')], max_length=50, verbose_name='Услуга')),
                ('question_number', models.IntegerField(verbose_name='Номер вопроса')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['service', 'question_number'],
            },
        ),
    ]
