# Generated by Django 5.1.6 on 2025-11-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_window', '0003_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=20, unique=True, verbose_name='Номер заявки')),
                ('service_type', models.CharField(max_length=200, verbose_name='Тип услуги')),
                ('format', models.CharField(blank=True, max_length=200, verbose_name='Формат')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Контактное лицо')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительные пожелания')),
                ('agreed_to_terms', models.BooleanField(verbose_name='Согласие с условиями')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В обработке'), ('completed', 'Завершено')], default='new', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка на услугу',
                'verbose_name_plural': 'Заявки на услуги',
            },
        ),
    ]
