# Generated by Django 5.2.8 on 2025-12-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_window', '0005_alter_servicerequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان السلايدر')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='العنوان الفرعي')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('image', models.ImageField(upload_to='slider_images/', verbose_name='الصورة')),
                ('link', models.URLField(blank=True, verbose_name='الرابط')),
                ('link_text', models.CharField(blank=True, max_length=100, verbose_name='نص الرابط')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'سلايدر',
                'verbose_name_plural': 'السلايدرات',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
