# Generated by Django 5.2.8 on 2026-02-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_window', '0007_alter_slider_options_alter_slider_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['service', 'question_number'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуга'},
        ),
    ]
