# Generated by Django 5.2.8 on 2026-02-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_window', '0008_alter_faq_options_alter_servicerequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['service', 'question_number'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на услугу', 'verbose_name_plural': 'Заявки на услуги'},
        ),
    ]
