# Generated by Django 5.2.8 on 2026-02-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_window', '0009_alter_faq_options_alter_servicerequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='service',
            field=models.CharField(choices=[('oformit-spravku', 'Оформить справку'), ('poluchit-dokumenty', 'Получить/Направить материнский капитал для обучения детей'), ('poluchit-materialnuyu-podderzhku', 'Получить материальную поддержку'), ('napravit-materinskiy-kapital', 'Направить материнский капитал для обучения детей'), ('oformit-chitatelskiy-bilet', 'Оформить читательский билет'), ('izmenit-lichnye-dannye', 'Изменить личные данные, отчислиться, оформить каникулы'), ('obrazovatelnyy-kredit', 'Образовательный кредит с господдержкой'), ('poluchit-lgotu', 'Получить льготу на образование')], max_length=50, verbose_name='Услуга'),
        ),
    ]
