# Generated by Django 5.2.8 on 2026-03-16 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_company'),
        ('single_window', '0010_alter_faq_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='accounts.company', verbose_name='Компания'),
        ),
    ]
