# Generated by Django 5.1.6 on 2025-11-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании/организации')),
                ('description', models.TextField(verbose_name='Описание')),
                ('partner_type', models.CharField(choices=[('government', 'Государственные организации'), ('business', 'Бизнес-сообщество'), ('education', 'Образовательные учреждения'), ('other', 'Другие')], max_length=20, verbose_name='Тип партнера')),
                ('logo', models.ImageField(upload_to='partners/logos/', verbose_name='Логотип')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('physical', 'Физическое лицо'), ('legal', 'Юридическое лицо')], max_length=10, verbose_name='Тип заявителя')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Контактное лицо')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('processed', 'Обработано')], default='pending', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка на партнерство',
                'verbose_name_plural': 'Заявки на партнерство',
                'ordering': ['-created_at'],
            },
        ),
    ]
