# Generated by Django 5.1.6 on 2025-11-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_contactmessage_faq_homeslider_logocarousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('image', models.ImageField(upload_to='home_sliders/', verbose_name='Изображение')),
                ('button_text', models.CharField(default='Оставить заявку на партнерство', max_length=100, verbose_name='Текст кнопки')),
                ('button_link', models.CharField(default='#', max_length=255, verbose_name='Ссылка кнопки')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Слайдер главной страницы',
                'verbose_name_plural': 'Слайдеры главной страницы',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='show_in_carousel',
            field=models.BooleanField(default=True, verbose_name='Показывать в карусели'),
        ),
        migrations.AddField(
            model_name='partner',
            name='show_in_grid',
            field=models.BooleanField(default=True, verbose_name='Показывать в сетке'),
        ),
    ]
