# Generated by Django 5.1.6 on 2025-11-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_homepageslider_partner_show_in_carousel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipapplication',
            name='request_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер заявки'),
        ),
    ]
