# Generated by Django 5.2.8 on 2026-02-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_partnershipapplication_request_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
