# Generated by Django 5.2.8 on 2026-02-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_delete_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='HomeSlider',
        ),
    ]
