# Generated by Django 5.1.6 on 2025-11-18 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoworkingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الفعالية')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('date', models.DateTimeField(verbose_name='تاريخ الفعالية')),
                ('duration', models.CharField(max_length=100, verbose_name='المدة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الدخول')),
                ('image', models.ImageField(upload_to='coworking/events/', verbose_name='صورة الفعالية')),
                ('max_attendees', models.IntegerField(verbose_name='الحد الأقصى للحضور')),
                ('current_attendees', models.IntegerField(default=0, verbose_name='عدد الحضور الحالي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'فعالية كوركينج',
                'verbose_name_plural': 'فعاليات الكوركينج',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='CoworkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المساحة')),
                ('space_type', models.CharField(choices=[('shared', 'مساحة مشتركة'), ('private_office', 'مكتب خاص'), ('meeting_room', 'قاعة اجتماعات'), ('event_space', 'مساحة فعاليات')], max_length=20, verbose_name='نوع المساحة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('capacity', models.IntegerField(verbose_name='السعة')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر لكل ساعة')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر لكل يوم')),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر لكل شهر')),
                ('image', models.ImageField(upload_to='coworking/', verbose_name='صورة المساحة')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاحة')),
                ('features', models.TextField(help_text='افصل بين المميزات بفاصلة', verbose_name='المميزات')),
            ],
            options={
                'verbose_name': 'مساحة كوركينج',
                'verbose_name_plural': 'مساحات الكوركينج',
            },
        ),
        migrations.CreateModel(
            name='CoworkingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='coworking/gallery/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='التعليق')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coworking.coworkingspace', verbose_name='المساحة')),
            ],
            options={
                'verbose_name': 'صورة كوركينج',
                'verbose_name_plural': 'معرض الصور',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ النهاية')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الإجمالي')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('special_requests', models.TextField(blank=True, verbose_name='طلبات خاصة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coworking.coworkingspace', verbose_name='المساحة')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'ordering': ['-created_at'],
            },
        ),
    ]
