# Generated by Django 5.1.6 on 2025-11-19 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Правила посещения пространства', max_length=200, verbose_name='Заголовок')),
                ('button_text', models.CharField(default='Стать башнером', max_length=100, verbose_name='Текст кнопки')),
                ('description', models.TextField(default='Мы создали пространство для тех, кто ценит тишину для концентрации, вдохновляющую атмосферу для творчества и гибкость для свободы выбора.', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='coworkingevent',
            options={'ordering': ['date'], 'verbose_name': 'Мероприятие коворкинга', 'verbose_name_plural': 'Мероприятия коворкинга'},
        ),
        migrations.AlterModelOptions(
            name='coworkingimage',
            options={'ordering': ['order'], 'verbose_name': 'Изображение коворкинга', 'verbose_name_plural': 'Галерея изображений'},
        ),
        migrations.AlterModelOptions(
            name='coworkingspace',
            options={'verbose_name': 'Пространство коворкинга', 'verbose_name_plural': 'Пространства коворкинга'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(max_length=200, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coworking.coworkingspace', verbose_name='Пространство'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, verbose_name='Особые пожелания'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='coworkingevent',
            name='current_attendees',
            field=models.IntegerField(default=0, verbose_name='Текущее количество участников'),
        ),
        migrations.AlterField(
            model_name='coworkingevent',
            name='date',
            field=models.DateTimeField(verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='coworkingevent',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='coworkingevent',
            name='duration',
            field=models.CharField(max_length=100, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='coworkingevent',
            name='image',
            field=models.ImageField(upload_to='coworking/events/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='coworkingevent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='coworkingevent',
            name='max_attendees',
            field=models.IntegerField(verbose_name='Максимум участников'),
        ),
        migrations.AlterField(
            model_name='coworkingevent',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость входа'),
        ),
        migrations.AlterField(
            model_name='coworkingevent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='coworkingimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='coworkingimage',
            name='image',
            field=models.ImageField(upload_to='coworking/gallery/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='coworkingimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='coworkingimage',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coworking.coworkingspace', verbose_name='Пространство'),
        ),
        migrations.AlterField(
            model_name='coworkingspace',
            name='capacity',
            field=models.IntegerField(verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='coworkingspace',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='coworkingspace',
            name='features',
            field=models.TextField(help_text='Перечислите через запятую', verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='coworkingspace',
            name='image',
            field=models.ImageField(upload_to='coworking/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='coworkingspace',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступно'),
        ),
        migrations.AlterField(
            model_name='coworkingspace',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название пространства'),
        ),
        migrations.AlterField(
            model_name='coworkingspace',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за день'),
        ),
        migrations.AlterField(
            model_name='coworkingspace',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за час'),
        ),
        migrations.AlterField(
            model_name='coworkingspace',
            name='price_per_month',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за месяц'),
        ),
        migrations.AlterField(
            model_name='coworkingspace',
            name='space_type',
            field=models.CharField(choices=[('shared', 'Общее пространство'), ('private_office', 'Приватный офис'), ('meeting_room', 'Переговорная'), ('event_space', 'Пространство для мероприятий')], max_length=20, verbose_name='Тип пространства'),
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='coworking.slider', verbose_name='Слайдер')),
            ],
            options={
                'verbose_name': 'Изображение слайдера',
                'verbose_name_plural': 'Изображения слайдера',
                'ordering': ['order'],
            },
        ),
    ]
