# Generated by Django 5.1.6 on 2025-11-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0002_slider_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='space',
        ),
        migrations.DeleteModel(
            name='CoworkingEvent',
        ),
        migrations.RemoveField(
            model_name='coworkingimage',
            name='space',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='CoworkingImage',
        ),
        migrations.DeleteModel(
            name='CoworkingSpace',
        ),
    ]
