# Generated by Django 5.1.6 on 2025-11-19 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0003_remove_booking_space_delete_coworkingevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название тарифа')),
                ('tariff_type', models.CharField(choices=[('trial', 'Пробный день'), ('flex', 'Гибкий график'), ('office', 'Закрытый кабинет')], max_length=20, verbose_name='Тип тарифа')),
                ('price', models.CharField(help_text='Например: Бесплатно, от 500 ₽ / час, от 2000 ₽ / день', max_length=100, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='tariffs/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('features', models.TextField(help_text='Разделяйте черточками', verbose_name='Особенности')),
                ('button_text', models.CharField(default='Забронировать', max_length=100, verbose_name='Текст кнопки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TariffFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(max_length=200, verbose_name='Особенность')),
                ('icon_name', models.CharField(help_text='Например: material-symbols:work, solar:tea-cup-bold', max_length=100, verbose_name='Название иконки')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_features', to='coworking.tariff')),
            ],
            options={
                'verbose_name': 'Особенность тарифа',
                'verbose_name_plural': 'Особенности тарифов',
                'ordering': ['order'],
            },
        ),
    ]
