# Generated by Django 5.1.6 on 2025-11-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0004_tariff_tarifffeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='features',
        ),
        migrations.AlterField(
            model_name='tariff',
            name='tariff_type',
            field=models.CharField(choices=[('trial', 'Пробный день'), ('flex', 'Гибкий график'), ('office', 'Закрытый кабинет'), ('common_hall', 'Общий зал'), ('meeting_room', 'Переговорный кабинет'), ('executive_office', 'Кабинет руководителя')], max_length=20, verbose_name='Тип тарифа'),
        ),
    ]
