# Generated by Django 5.1.6 on 2025-11-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0005_remove_tariff_features_alter_tariff_tariff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tariffs/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='tariff_type',
            field=models.CharField(choices=[('trial', 'Пробный день'), ('flex', 'Гибкий график'), ('office', 'Закрытый кабинет'), ('meeting_room', 'Переговорный кабинет'), ('executive_office', 'Кабинет руководителя')], max_length=20, verbose_name='Тип тарифа'),
        ),
    ]
