# Generated by Django 5.2.8 on 2026-03-13 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_company_remove_profile_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='Компания (для аккаунтов компаний и сотрудников)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Администратор'), ('regular', 'Обычный пользователь'), ('teacher', 'Преподаватель'), ('student', 'Студент'), ('company', 'Компания')], default='regular', max_length=20, verbose_name='Тип пользователя'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
