# Generated by Django 5.2.8 on 2026-03-16 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_subscription_plan_remove_subscription_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.company', verbose_name='Компания (для аккаунтов компаний и сотрудников)'),
        ),
    ]
