# Generated by Django 5.2.8 on 2025-12-26 15:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Уникальный номер заявки'),
        ),
    ]
