# Generated by Django 5.2.8 on 2026-02-27 15:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название выпуска')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cover_image', models.ImageField(upload_to='journal/covers/', verbose_name='Изображение обложки')),
                ('publication_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='journal/pdfs/', verbose_name='PDF файл')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('show_in_best', models.BooleanField(default=False, verbose_name='Показать в разделе Лучшее')),
                ('show_in_new', models.BooleanField(default=False, verbose_name='Показать в разделе Новые поступления')),
                ('best_order', models.IntegerField(default=0, verbose_name='Порядок в разделе Лучшее')),
                ('new_order', models.IntegerField(default=0, verbose_name='Порядок в разделе Новые поступления')),
            ],
            options={
                'verbose_name': 'Выпуск журнала',
                'verbose_name_plural': 'Выпуски журнала',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='SectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_section_title', models.CharField(default='Лучшее', max_length=100, verbose_name='Название раздела Лучшее')),
                ('new_section_title', models.CharField(default='Новые поступления', max_length=100, verbose_name='Название раздела Новые поступления')),
                ('early_section_title', models.CharField(default='Ранние выпуски', max_length=100, verbose_name='Название раздела Ранние выпуски')),
            ],
            options={
                'verbose_name': 'Настройки разделов',
                'verbose_name_plural': 'Настройки разделов',
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название изображения')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание изображения')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('carousel_type', models.CharField(choices=[('main', 'Main Slider'), ('best', 'Лучшее Carousel'), ('early', 'Ранние выпуски Carousel')], default='main', max_length=10, verbose_name='Тип карусели')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Изображение слайдера',
                'verbose_name_plural': 'Изображения слайдера',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssuePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='journal/pages/', verbose_name='Изображение страницы')),
                ('page_number', models.PositiveIntegerField(verbose_name='Номер страницы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='fta_journal.journalissue', verbose_name='Выпуск')),
            ],
            options={
                'verbose_name': 'Страница выпуска',
                'verbose_name_plural': 'Страницы выпусков',
                'ordering': ['issue', 'order', 'page_number'],
            },
        ),
    ]
