# Generated by Django 5.2.8 on 2025-12-17 16:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0004_contactrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название программы')),
                ('program_type', models.CharField(choices=[('professional_retraining', 'Профессиональная переподготовка'), ('qualification_upgrade', 'Повышение квалификации'), ('seminar', 'Семинар'), ('training', 'Тренинг'), ('other', 'Другое')], max_length=50, verbose_name='Тип программы')),
                ('certification_type', models.CharField(choices=[('certified', 'Сертифицированные программы'), ('diploma', 'Дипломированные программы'), ('attestation', 'Удостоверительные программы'), ('none', 'Без сертификации')], default='none', max_length=50, verbose_name='Тип сертификации')),
                ('format', models.CharField(choices=[('offline', 'Очно'), ('blended', 'Очно-заочно'), ('correspondence', 'Заочно'), ('online', 'Онлайн')], default='offline', max_length=20, verbose_name='Формат')),
                ('detailed_description', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='schedule/side_images/', verbose_name='Боковое изображение')),
                ('diploma_image_1', models.ImageField(blank=True, null=True, upload_to='schedule/diplomas/', verbose_name='Дипломное изображение 1')),
                ('diploma_image_2', models.ImageField(blank=True, null=True, upload_to='schedule/diplomas/', verbose_name='Дипломное изображение 2')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Длительность')),
                ('duration_hours', models.IntegerField(default=0, verbose_name='Количество часов')),
                ('image', models.ImageField(blank=True, null=True, upload_to='schedule/', verbose_name='Изображение')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('enrollment_status', models.CharField(choices=[('open', 'Набор открыт'), ('closed', 'Набор закрыт'), ('upcoming', 'Предстоящий'), ('archive', 'Архив'), ('on_request', 'По запросу')], default='open', max_length=20, verbose_name='Статус набора')),
                ('schedule_description', models.TextField(blank=True, help_text="Текст для раздела 'Расписание занятий'", verbose_name='Описание расписания')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='departments.department', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Программа расписания',
                'verbose_name_plural': 'Программы расписания',
                'ordering': ['start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название документа')),
                ('document_type', models.CharField(choices=[('word', 'Word документ'), ('excel', 'Excel документ'), ('pdf', 'PDF документ'), ('other', 'Другой документ')], default='pdf', max_length=10, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='schedule/documents/', verbose_name='Файл')),
                ('description', models.TextField(blank=True, verbose_name='Описание документа')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='schedule.scheduleprogram', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Документ программы',
                'verbose_name_plural': 'Документы программ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=20, unique=True, verbose_name='Номер заявки')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Контактное лицо')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительные пожелания')),
                ('agreement', models.BooleanField(default=False, verbose_name='Согласие с условиями')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduleprogram', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Заявка на обучение',
                'verbose_name_plural': 'Заявки на обучение',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название модуля')),
                ('description', models.TextField(blank=True, verbose_name='Описание модуля')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_modules', to='schedule.scheduleprogram', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Модуль учебной программы',
                'verbose_name_plural': 'Модули учебной программы',
                'ordering': ['order', 'id'],
            },
        ),
    ]
