# Generated by Django 5.2.6 on 2025-12-18 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedulesliderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название документа')),
                ('document_type', models.CharField(choices=[('word', 'Word документ'), ('excel', 'Excel документ'), ('pdf', 'PDF документ'), ('other', 'Другой документ')], default='pdf', max_length=10, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='schedule/curriculum_documents/', verbose_name='Файл')),
                ('description', models.TextField(blank=True, verbose_name='Описание документа')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_documents', to='schedule.scheduleprogram', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Документ программы обучения',
                'verbose_name_plural': 'Документы программ обучения',
                'ordering': ['order', 'id'],
            },
        ),
    ]
