# Generated by Django 5.2.8 on 2026-02-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_curriculumdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleprogram',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
