# Generated by Django 5.2.8 on 2026-02-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_scheduleprogram_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='schedule/calendar_slider/', verbose_name='Изображение слайдера')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('link_text', models.CharField(blank=True, max_length=100, verbose_name='Текст ссылки')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Изображение слайдера календаря',
                'verbose_name_plural': 'Изображения слайдера календаря',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
