# Generated by Django 5.2.8 on 2026-02-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_calendarsliderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleprogram',
            name='admission_description',
            field=models.TextField(blank=True, help_text="Текст для раздела 'Как поступить'", verbose_name='Текст условий поступления'),
        ),
        migrations.AddField(
            model_name='scheduleprogram',
            name='admission_file',
            field=models.FileField(blank=True, help_text='Загрузите файл с образцом заявления на поступление (PDF, Word)', null=True, upload_to='schedule/admission_files/', verbose_name='Образец заявления на поступление'),
        ),
        migrations.AddField(
            model_name='scheduleprogram',
            name='schedule_file',
            field=models.FileField(blank=True, help_text='Загрузите файл с подробным расписанием занятий (PDF, Word, Excel)', null=True, upload_to='schedule/schedule_files/', verbose_name='Файл расписания занятий'),
        ),
        migrations.AlterField(
            model_name='scheduleprogram',
            name='schedule_description',
            field=models.TextField(blank=True, help_text="Текст для раздела 'Расписание занятий'", verbose_name='Текст расписания занятий'),
        ),
    ]
