# Generated by Django 5.2.8 on 2026-02-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_scheduleprogram_admission_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleprogram',
            name='admission_description',
        ),
        migrations.RemoveField(
            model_name='scheduleprogram',
            name='admission_file',
        ),
        migrations.RemoveField(
            model_name='scheduleprogram',
            name='schedule_file',
        ),
        migrations.AlterField(
            model_name='scheduleprogram',
            name='schedule_description',
            field=models.TextField(blank=True, help_text="Текст для раздела 'Расписание занятий'", verbose_name='Описание расписания'),
        ),
    ]
