# Generated by Django 5.2.8 on 2026-02-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_scheduledocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleDocument',
        ),
    ]
