# Generated by Django 5.2.8 on 2026-02-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_delete_programdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleprogram',
            name='schedule_document',
            field=models.FileField(blank=True, help_text='Загрузите файл расписания программ обучения (PDF, Word, Excel)', null=True, upload_to='schedule/schedule_documents/', verbose_name='Файл расписания программ обучения'),
        ),
        migrations.AlterField(
            model_name='scheduleprogram',
            name='schedule_description',
            field=models.TextField(blank=True, help_text="Текст для раздела 'Расписание занятий'. Если оставить пустым, будет использован текст по умолчанию.", verbose_name='Описание расписания'),
        ),
    ]
