# Generated by Django 5.2.8 on 2026-02-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_scheduleprogram_schedule_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleprogram',
            name='admission_application_sample',
            field=models.FileField(blank=True, help_text='Загрузите образец заявления на поступление', null=True, upload_to='schedule/admission_documents/', verbose_name='Образец заявления на поступление'),
        ),
        migrations.AddField(
            model_name='scheduleprogram',
            name='admission_documents',
            field=models.TextField(blank=True, help_text="Введите текст для раздела 'Документы для поступления'", verbose_name='Документы для поступления'),
        ),
        migrations.AddField(
            model_name='scheduleprogram',
            name='admission_requirements',
            field=models.TextField(blank=True, help_text="Введите текст для раздела 'Требования к слушателям'", verbose_name='Требования к слушателям'),
        ),
        migrations.AddField(
            model_name='scheduleprogram',
            name='target_audience',
            field=models.TextField(blank=True, help_text="Введите текст для раздела 'Для кого предназначена программа'", verbose_name='Для кого предназначена программа'),
        ),
    ]
