# Generated by Django 5.2.8 on 2026-02-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_scheduleprogram_admission_application_sample_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleprogram',
            name='admission_application_sample',
        ),
        migrations.RemoveField(
            model_name='scheduleprogram',
            name='admission_documents',
        ),
        migrations.RemoveField(
            model_name='scheduleprogram',
            name='admission_requirements',
        ),
        migrations.RemoveField(
            model_name='scheduleprogram',
            name='target_audience',
        ),
    ]
