# Generated by Django 5.2.8 on 2026-02-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_remove_scheduleprogram_admission_application_sample_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleprogram',
            name='admission_form_document',
            field=models.FileField(blank=True, help_text='Загрузите образец заявления на поступление (PDF, Word, Excel)', null=True, upload_to='schedule/admission_forms/', verbose_name='Образец заявления на поступление'),
        ),
        migrations.AddField(
            model_name='scheduleprogram',
            name='admission_requirements',
            field=models.TextField(blank=True, help_text='Оставьте пустым, чтобы использовать стандартный текст', verbose_name='Требования к слушателям и документы для поступления'),
        ),
    ]
