# Generated by Django 5.2.8 on 2026-02-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_scheduleprogram_admission_form_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleprogram',
            name='target_audience',
            field=models.TextField(blank=True, help_text='Введите каждый пункт списка с новой строки. Если оставить пустым, будет использован текст по умолчанию.', verbose_name='Целевая аудитория (каждый пункт с новой строки)'),
        ),
    ]
