# Generated by Django 5.2.8 on 2026-02-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_scheduleprogram_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleprogram',
            name='postponed_date',
            field=models.DateField(blank=True, help_text='Укажите дату, на которую перенесена программа (для статуса «Перенесен на»)', null=True, verbose_name='Перенесено на дату'),
        ),
        migrations.AlterField(
            model_name='scheduleprogram',
            name='enrollment_status',
            field=models.CharField(choices=[('open', 'Набор открыт'), ('closed', 'Набор закрыт'), ('upcoming', 'Предстоящий'), ('archive', 'Архив'), ('on_request', 'По запросу'), ('postponed', 'Перенесен на')], default='open', max_length=20, verbose_name='Статус набора'),
        ),
    ]
