# Generated by Django 5.2.8 on 2026-03-16 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_company'),
        ('schedule', '0016_scheduleprogram_postponed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarsliderimage',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_slider_images', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='curriculumdocument',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_documents', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='curriculummodule',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_modules', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='programapplication',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_applications', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='scheduleprogram',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_programs', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='schedulesliderimage',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slider_images', to='accounts.company', verbose_name='Компания'),
        ),
    ]
