# Generated by Django 5.2.8 on 2026-02-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='message_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Хеш сообщения'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID сессии'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['email', 'created_at'], name='contact_for_email_9f131e_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['session_id', 'created_at'], name='contact_for_session_d6defd_idx'),
        ),
    ]
