# Generated by Django 5.2.8 on 2026-02-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0002_contactmessage_message_hash_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contactmessage',
            name='contact_for_email_9f131e_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactmessage',
            name='contact_for_session_d6defd_idx',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='message_hash',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='session_id',
        ),
    ]
