# Generated by Django 5.2.8 on 2026-02-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0003_remove_contactmessage_contact_for_email_9f131e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Хэш сообщения'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
    ]
