# Generated by Django 5.2.8 on 2026-02-01 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0004_contactmessage_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='message_hash',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='user_agent',
        ),
    ]
