# Generated by Django 5.2.8 on 2026-02-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0005_remove_contactmessage_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='email_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Хеш email'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['email_hash', 'created_at'], name='contact_for_email_h_79a0c2_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['client_ip', 'created_at'], name='contact_for_client__878426_idx'),
        ),
    ]
