# Generated by Django 5.2.8 on 2026-03-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0006_contactmessage_client_ip_contactmessage_email_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Заметки администратора'),
        ),
    ]
