# Generated by Django 5.2.8 on 2026-03-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0007_contactmessage_admin_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='admin_notes',
        ),
    ]
