# Generated by Django 5.2.8 on 2026-02-19 22:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadableFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Презентация', max_length=200, verbose_name='Название файла')),
                ('description', models.TextField(blank=True, verbose_name='Описание файла')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('word', 'Word'), ('powerpoint', 'PowerPoint')], default='pdf', max_length=15, verbose_name='Тип файла')),
                ('file', models.FileField(help_text='Загрузите файл PDF, Excel, Word или PowerPoint', upload_to='downloadable_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xlsx', 'xls', 'docx', 'doc', 'pptx', 'ppt'])], verbose_name='Файл')),
                ('button_text', models.CharField(default='Скачать презентацию', max_length=100, verbose_name='Текст кнопки')),
                ('button_color', models.CharField(default='#7F1726', help_text='Введите HEX-код цвета (пример: #7F1726)', max_length=7, verbose_name='Цвет кнопки')),
                ('text_color', models.CharField(default='#FDFDFD', help_text='Введите HEX-код цвета (пример: #FDFDFD)', max_length=7, verbose_name='Цвет текста')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('position_right', models.BooleanField(default=True, verbose_name='Позиция справа')),
                ('show_icon', models.BooleanField(default=True, verbose_name='Показывать иконку')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Файл для скачивания',
                'verbose_name_plural': 'Файлы для скачивания',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.TextField(verbose_name='Должность (можно с переносами)')),
                ('image', models.ImageField(upload_to='about_academy/leadership/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководство',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LeaderSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Речь руководителя', max_length=200, verbose_name='Заголовок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Речь руководителя',
                'verbose_name_plural': 'Речь руководителя',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок слайда')),
                ('description', models.TextField(blank=True, verbose_name='Описание слайда')),
                ('image', models.ImageField(upload_to='main_slider/', verbose_name='Изображение слайда')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Слайд главной страницы',
                'verbose_name_plural': 'Слайды главной страницы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название альбома')),
                ('cover_image', models.ImageField(upload_to='about_academy/albums/covers/', verbose_name='Обложка альбома')),
                ('description', models.TextField(blank=True, verbose_name='Описание альбома')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Фотоальбом',
                'verbose_name_plural': 'Фотоальбомы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuoteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Цитата', max_length=200, verbose_name='Заголовок')),
                ('quote_text', models.TextField(verbose_name='Текст цитаты')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_academy/quotes/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Цитата (под ценностями)',
                'verbose_name_plural': 'Цитаты (под ценностями)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StatisticsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Академия в цифрах', max_length=200, verbose_name='Заголовок')),
                ('stat_title', models.CharField(default='К образовательным программам', max_length=200, verbose_name='Заголовок статистики')),
                ('stat_number_1', models.CharField(default='20 000', max_length=50, verbose_name='Число 1')),
                ('stat_label_1', models.CharField(default='Тысяч выпущенных учеников', max_length=200, verbose_name='Подпись 1')),
                ('stat_number_2', models.CharField(default='380', max_length=50, verbose_name='Число 2')),
                ('stat_label_2', models.CharField(default='Телефонных звонков', max_length=200, verbose_name='Подпись 2')),
                ('stat_number_3', models.CharField(default='983', max_length=50, verbose_name='Число 3')),
                ('stat_label_3', models.CharField(default='Котят', max_length=200, verbose_name='Подпись 3')),
                ('content', models.TextField(blank=True, verbose_name='Дополнительный контент')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('show_dot', models.BooleanField(default=True, verbose_name='Показывать точку')),
                ('show_arrow', models.BooleanField(default=True, verbose_name='Показывать стрелку')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': "Раздел 'Академия в цифрах'",
                'verbose_name_plural': "Разделы 'Академия в цифрах'",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ValuesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Наши ценности', max_length=200, verbose_name='Заголовок')),
                ('rocket_image', models.ImageField(blank=True, null=True, upload_to='about_academy/values/', verbose_name='Изображение ракеты')),
                ('quote_1', models.TextField(default='Мы создаем свободное пространство для идей и развития, помогая проявить достаточно смелости, чтобы воплотить их в жизнь с верой в себя.', verbose_name='Цитата 1')),
                ('quote_2', models.TextField(default='Наша уникальность заключается в объединении четырех школ: Академии Аристотеля, Майевтики Сократа, Мастерской да Винчи и Методики воспитания силы воли Сеченова.', verbose_name='Цитата 2')),
                ('content', models.TextField(blank=True, verbose_name='Дополнительный контент')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('show_dot', models.BooleanField(default=True, verbose_name='Показывать точку')),
                ('show_arrow', models.BooleanField(default=True, verbose_name='Показывать стрелку')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': "Раздел 'Наши ценности'",
                'verbose_name_plural': "Разделы 'Наши ценности'",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LeaderSpeechVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название видео')),
                ('video_url', models.URLField(blank=True, help_text='Ссылка на YouTube или другое видео (необязательно, если загружаете файл)', null=True, verbose_name='Ссылка на видео')),
                ('video_file', models.FileField(blank=True, help_text='Загрузите видео файл (MP4, AVI, MOV, WMV, FLV, WEBM)', null=True, upload_to='leader_speech/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm'])], verbose_name='Видео файл')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='leader_speech/thumbnails/', verbose_name='Превью видео')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('leader_speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='about_academy.leaderspeech', verbose_name='Речь руководителя')),
            ],
            options={
                'verbose_name': 'Видео речи руководителя',
                'verbose_name_plural': 'Видео речи руководителя',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_academy/gallery/%Y/%m/%d/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись к изображению')),
                ('description', models.TextField(blank=True, verbose_name='Описание изображения')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('album', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about_academy.photoalbum', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Изображения галереи',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
