# Generated by Django 5.2.8 on 2026-02-19 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_academy', '0002_remove_galleryimage_caption_galleryimage_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='title',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подпись к изображению'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about_academy.photoalbum', verbose_name='Альбом'),
        ),
    ]
