# Generated by Django 5.2.8 on 2026-02-19 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_academy', '0003_remove_galleryimage_title_galleryimage_caption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='description',
        ),
    ]
