# Generated by Django 5.2.8 on 2026-02-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_academy', '0005_alter_galleryimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='Можно выбрать несколько файлов одновременно', upload_to='about_academy/gallery/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
