# Generated by Django 5.2.8 on 2026-02-20 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_academy', '0006_alter_galleryimage_image'),
        ('departments', '0006_delete_contactrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('image', models.ImageField(upload_to='about_academy/team/', verbose_name='Фото')),
                ('position', models.TextField(verbose_name='Должность (можно с переносами)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('rank', models.CharField(choices=[('director', 'Директор'), ('deputy_director', 'Заместитель директора'), ('teacher', 'Преподаватель'), ('employee', 'Сотрудник')], default='employee', max_length=20, verbose_name='Иерархический ранг')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок внутри ранга')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academy_team_members', to='departments.department', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Член команды (Об академии)',
                'verbose_name_plural': 'Члены команды (Об академии)',
                'ordering': ['department', 'rank', 'order'],
            },
        ),
    ]
