# Generated by Django 5.2.6 on 2025-11-11 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория исследований',
                'verbose_name_plural': 'Категории исследований',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название исследования')),
                ('research_type', models.CharField(choices=[('fundamental', 'Фундаментальные исследования'), ('business_management', 'Управление бизнесом и персоналом'), ('education', 'Исследования в образовании'), ('publishing', 'Издательско-полиграфические исследования'), ('psychological', 'Психологические исследования')], max_length=50, verbose_name='Тип исследования')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='research/', verbose_name='Изображение')),
                ('publication_date', models.DateField(verbose_name='Дата публикации')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('file', models.FileField(blank=True, null=True, upload_to='research/files/', verbose_name='Файл исследования')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.researchcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Исследование',
                'verbose_name_plural': 'Исследования',
                'ordering': ['-publication_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тега')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('research', models.ManyToManyField(related_name='tags', to='research.research', verbose_name='Исследования')),
            ],
            options={
                'verbose_name': 'Тег исследования',
                'verbose_name_plural': 'Теги исследований',
            },
        ),
    ]
