# Generated by Django 5.2.8 on 2026-02-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchListBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='research/banners/', verbose_name='Изображение баннера')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (необязательно)')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок (необязательно)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Баннер страницы списка исследований',
                'verbose_name_plural': 'Баннеры страницы списка исследований',
            },
        ),
        migrations.AddField(
            model_name='research',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='research/hero/', verbose_name='Изображение героя (для страницы деталей)'),
        ),
    ]
