# Generated by Django 5.2.8 on 2026-02-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_researchlistbanner_research_hero_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResearchListBanner',
        ),
        migrations.RemoveField(
            model_name='research',
            name='hero_image',
        ),
    ]
