# Generated by Django 5.2.8 on 2026-02-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_delete_researchlistbanner_remove_research_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (необязательно)')),
                ('background_image', models.ImageField(help_text='Рекомендуемый размер: широкий формат, например 1920x600', upload_to='research/hero/', verbose_name='Фоновое изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero для исследований',
                'verbose_name_plural': 'Hero для исследований',
            },
        ),
    ]
