# Generated by Django 5.2.8 on 2026-02-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_researchhero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название конференции')),
                ('conference_type', models.CharField(choices=[('international', 'Международная'), ('national', 'Национальная'), ('regional', 'Региональная'), ('online', 'Онлайн')], max_length=50, verbose_name='Тип конференции')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='conferences/', verbose_name='Изображение')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('location', models.CharField(max_length=300, verbose_name='Место проведения')),
                ('registration_link', models.URLField(blank=True, verbose_name='Ссылка для регистрации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Конференция',
                'verbose_name_plural': 'Конференции',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
