# Generated by Django 5.2.8 on 2026-02-23 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_conference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('agreement', models.BooleanField(verbose_name='Согласие с условиями')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Номер регистрации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='research.conference', verbose_name='Конференция')),
            ],
            options={
                'verbose_name': 'Регистрация на конференцию',
                'verbose_name_plural': 'Регистрации на конференции',
                'ordering': ['-created_at'],
            },
        ),
    ]
