# Generated by Django 5.2.8 on 2026-02-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_conferenceregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConferenceRegistration',
        ),
    ]
