# Generated by Django 5.2.6 on 2026-02-23 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_delete_conferenceregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Контактный email'),
        ),
        migrations.AddField(
            model_name='conference',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='conference',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон'),
        ),
        migrations.AddField(
            model_name='conference',
            name='organizers',
            field=models.TextField(blank=True, verbose_name='Организаторы'),
        ),
        migrations.AddField(
            model_name='conference',
            name='video',
            field=models.FileField(blank=True, help_text='Загрузите короткое видео (до 30 секунд, MP4) о том, как добраться до места.', null=True, upload_to='conferences/videos/', verbose_name='Видео (как дойти)'),
        ),
        migrations.AddField(
            model_name='conference',
            name='video_title',
            field=models.CharField(blank=True, default='Как дойти?', max_length=200, verbose_name='Заголовок видео'),
        ),
        migrations.CreateModel(
            name='ConferenceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('agreement', models.BooleanField(verbose_name='Согласие с условиями')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Номер регистрации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='research.conference', verbose_name='Конференция')),
            ],
            options={
                'verbose_name': 'Регистрация на конференцию',
                'verbose_name_plural': 'Регистрации на конференции',
                'ordering': ['-created_at'],
            },
        ),
    ]
