# Generated by Django 5.2.8 on 2026-02-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_conference_contact_email_conference_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='conferences/files/', verbose_name='Файл конференции'),
        ),
    ]
