# Generated by Django 5.2.8 on 2026-02-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_conference_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='entrance_fee',
            field=models.CharField(default='бесплатно', help_text='Например: бесплатно, 500 руб, по приглашениям', max_length=100, verbose_name='Вход (плата)'),
        ),
    ]
