# Generated by Django 5.2.8 on 2026-02-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_conference_entrance_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchhero',
            name='brochure',
            field=models.FileField(blank=True, help_text='Загрузите PDF-файл с брошюрой конференций', null=True, upload_to='research/brochures/', verbose_name='Брошюра конференций (PDF)'),
        ),
    ]
