# Generated by Django 5.2.8 on 2026-02-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_delete_contactrequest'),
        ('research', '0011_researchhero_brochure'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouthCouncilMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='youth_council/', verbose_name='Фото')),
                ('position', models.TextField(verbose_name='Должность')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('departments', models.ManyToManyField(blank=True, related_name='youth_council_members', to='departments.department', verbose_name='Отделения')),
            ],
            options={
                'verbose_name': 'Член молодежного ученого совета',
                'verbose_name_plural': 'Члены молодежного ученого совета',
                'ordering': ['order', 'name'],
            },
        ),
    ]
