# Generated by Django 5.2.8 on 2026-02-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_youthcouncilmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouthCouncilDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название отделения')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отделение молодежного совета',
                'verbose_name_plural': 'Отделения молодежного совета',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='youthcouncilmember',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='members', to='research.youthcouncildepartment', verbose_name='Отделения'),
        ),
    ]
