# Generated by Django 5.2.8 on 2026-03-16 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_company'),
        ('research', '0013_youthcouncildepartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conferences', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='conferenceregistration',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conference_registrations', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='research',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research', to='accounts.company', verbose_name='Компания'),
        ),
    ]
