# Generated by Django 5.2.6 on 2025-11-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название кафедры')),
                ('program_type', models.CharField(choices=[('economics', 'Кафедра экономики и управления'), ('psychology', 'Кафедра психологии'), ('law', 'Кафедра юриспруденции'), ('design', 'Кафедра дизайна'), ('management', 'Кафедра менеджмента'), ('development', 'Иные форматы развития')], max_length=50, verbose_name='Тип программы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='departments/', verbose_name='Изображение')),
                ('programs_count', models.IntegerField(default=0, verbose_name='Количество программ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
                'ordering': ['order', 'name'],
            },
        ),
    ]
