# Generated by Django 5.1.6 on 2025-11-11 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='programs_count',
        ),
    ]
