# Generated by Django 5.2.8 on 2025-12-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_remove_department_programs_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Отделение', 'verbose_name_plural': 'Отделения'},
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название отделения'),
        ),
        migrations.AlterField(
            model_name='department',
            name='program_type',
            field=models.CharField(choices=[('economics', 'Отделение экономики и управления'), ('psychology', 'Отделение психологии'), ('law', 'Отделение юриспруденции'), ('design', 'Отделение дизайна'), ('management', 'Отделение менеджмента'), ('development', 'Иные форматы развития')], max_length=50, verbose_name='Тип программы'),
        ),
    ]
