# Generated by Django 5.2.8 on 2025-12-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_contactrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('departments_list', 'Страница списка отделений'), ('department_detail', 'Страница деталей отделения')], max_length=50, unique=True, verbose_name='Страница')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='hero_images/', verbose_name='Изображение героя')),
                ('link_text', models.CharField(blank=True, max_length=100, verbose_name='Текст ссылки')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Изображение героя',
                'verbose_name_plural': 'Изображения героев',
                'ordering': ['order', 'page'],
            },
        ),
    ]
