# Generated by Django 5.2.8 on 2026-02-12 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_heroimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactRequest',
        ),
    ]
