# Generated by Django 5.2.8 on 2026-03-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_activitylog_archived_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activitylog',
            name='notificatio_timesta_604ec2_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='notificatio_action_6010e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='notificatio_user_id_106c93_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='notificatio_archive_e0e713_idx',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='archived',
        ),
    ]
